Updating sync-script and org file for it
* .scripts/backup-scripts/sync/sync-script:

diff --git a/.scripts/backup-scripts/sync/sync-script b/.scripts/backup-scripts/sync/sync-script
--- a/.scripts/backup-scripts/sync/sync-script
+++ b/.scripts/backup-scripts/sync/sync-script
@@ -1,48 +1,28 @@
-#!/bin/bash
-##____  _                      _
-#|  _ \| |__   ___   ___ _ __ (_)_  __
-#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
-#|  __/| | | | (_) |  __/ | | | |>  <
-#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
-#
-# -*- coding: utf-8 -*-
-#script that will compare all my config files and scripts to keep them up to date
-#if it detect one change its gonna update to all my locations so I always have the latest version
-#in my github repos etc
+#!/usr/bin/env bash
 
-# Define variables that are used in the script
 DOTFILES_REPO_PATH="$HOME/myrepos/dotfiles"
 DMSCRIPTS_REPO_PATH="$HOME/myrepos/dmscripts"
 
 RED=$(tput setaf 1)
 GREEN=$(tput setaf 2)
 
-# Declare the array that that contains files
-# that I want to sync to my github repos folder
 declare -A files
 
-# dmscripts
 files[$HOME/.dmenu]="$DMSCRIPTS_REPO_PATH/.dmenu"
-files[$HOME/.config]="$DMSCRIPTS_REPO_PATH/.config"
 
-# Scripts
 files[$HOME/.scripts/activated]="$DOTFILES_REPO_PATH/.scripts/activated"
 files[$HOME/.scripts/restart]="$DOTFILES_REPO_PATH/.scripts/restart"
 files[$HOME/.scripts/backup-scripts/sync]="$DOTFILES_REPO_PATH/.scripts/backup-scripts/sync"
 files[$HOME/.scripts/backup-scripts/btrfs]="$DOTFILES_REPO_PATH/.scripts/backup-scripts/btrfs"
 files[$HOME/.scripts/backup-scripts/yandex-script]="$DOTFILES_REPO_PATH/.scripts/yandex-script"
 
-# Docker
 files[$HOME/.scripts/docker]="$DOTFILES_REPO_PATH/.scripts/docker"
 
-# Alias files
-files[$HOME/Documents/lists]="$DOTFILES_REPO_PATH/Documents/lists"
-
-# Config files
 files[$HOME/.zshrc]="$DOTFILES_REPO_PATH/.zshrc"
+files[$HOME/.bashrc]="$DOTFILES_REPO_PATH/.bashrc"
 files[$HOME/.config/bash]="$DOTFILES_REPO_PATH/.config/bash"
 files[$HOME/.config/kitty/kitty.conf]="$DOTFILES_REPO_PATH/.config/kitty/kitty.conf"
-files[$HOME/.config/starship.toml]="$DOTFILES_REPO_PATH/.zshrc"
+files[$HOME/.config/starship.toml]="$DOTFILES_REPO_PATH/.config/starship.toml"
 files[$HOME/.config/qtile/config.py]="$DOTFILES_REPO_PATH/.config/qtile/config.py"
 files[$HOME/.config/qtile/autostart.sh]="$DOTFILES_REPO_PATH/.config/qtile/autostart.sh"
 files[$HOME/.config/qtile/themes]="$DOTFILES_REPO_PATH/.config/qtile/themes"
@@ -55,12 +35,34 @@ files[$HOME/.config/rofi/themes]="$DOTFILES_REPO_PATH/.config/rofi/themes"
 files[$HOME/.config/rofi/config.rasi]="$DOTFILES_REPO_PATH/.config/rofi/config.rasi"
 files[$HOME/.config/wofi]="$DOTFILES_REPO_PATH/.config/wofi"
 files[$HOME/.config/doom]="$DOTFILES_REPO_PATH/.config/doom"
+files[$HOME/.config/doom/eshell]="$DOTFILES_REPO_PATH/.config/doom/eshell"
 files[$HOME/.config/nvim/init.vim]="$DOTFILES_REPO_PATH/.config/nvim/init.vim"
 files[$HOME/.config/nvim/vim-plug]="$DOTFILES_REPO_PATH/.config/nvim/vim-plug"
-files[$HOME/.config/oh-my-zsh/aliases.sh]="$DOTFILES_REPO_PATH/.config/oh-my-zsh/aliases.sh"
+files[$HOME/.config/alias-zsh-bash]="$DOTFILES_REPO_PATH/.config/alias-zsh-bash"
+files[$HOME/.config/fish/conf.d/alias.fish]="$DOTFILES_REPO_PATH/.config/fish/conf.d/alias.fish"
+files[$HOME/.config/fish/config.fish]="$DOTFILES_REPO_PATH/.config/fish/config.fish"
 files[$HOME/.tmux.conf.local]="$DOTFILES_REPO_PATH/.tmux.conf.local"
 files[$HOME/.config/qutebrowser/config.py]="$DOTFILES_REPO_PATH/.config/qutebrowser/config.py"
 files[$HOME/.config/qutebrowser/quickmarks]="$DOTFILES_REPO_PATH/.config/qutebrowser/quickmarks"
+
+while getopts ":f:v" opt; do
+  case $opt in
+     f)
+      file="$OPTARG"
+      ;;
+     v)
+      flag=true
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
 
 for COMPARE in $(printf '%s\n' "${!files[@]}") ; do
 
@@ -68,10 +70,7 @@ if [ -d $COMPARE ] ; then
 
        SOURCE=$(printf '%s\n' $(printf '%s\n' "${files["${COMPARE}"]}") )
 
-
-
 for SOURCE_LOOP in $(ls  $SOURCE/* ) ; do
-
 
        DEST=$(echo $SOURCE_LOOP | sed -e "s|$DMSCRIPTS_REPO_PATH|$HOME|"  -e "s|$DOTFILES_REPO_PATH|$HOME|" )
 
@@ -83,7 +82,13 @@ if cmp --quiet $DEST $SOURCE_LOOP ; then
 
     else
 
-      echo -e "${RED}-- No Change Detected: ${DEST}"
+
+       if [ "$flag" = 'true' ] ; then
+
+
+             [ -z $DEST ] && echo "" &> /dev/null || echo -e "${RED}-- No Change Detected: ${DEST}"
+
+       fi
 
     fi
 
@@ -111,10 +116,13 @@ if [ "$SAME_NAME_OLDEST" = "$SAME_NAME_LATEST" ] ; then
 
        cp -r $LATEST $OLDEST 2> /dev/null
 
-       echo -e "${GREEN}++ Moving: ${LATEST} to ${OLDEST}"
+       if [ "$flag" = 'true' ] ; then
+
+       [ -z $LATEST ] && echo "" &> /dev/null || echo -e "${GREEN}++ Moving: ${LATEST} to ${OLDEST}"
 
        sleep 1
 
+       fi
 fi
 
 fi
@@ -136,7 +144,13 @@ if cmp --quiet $COMPARE $COMPARE_WITH ; then
 
     else
 
-      echo -e "${RED}-- No Change Detected: ${COMPARE}"
+
+       if [ "$flag" = 'true' ] ; then
+
+      [ -z $COMPARE ] && echo "" &> /dev/null || echo -e "${RED}-- No Change Detected: ${COMPARE}"
+
+
+       fi
 
     fi
 
@@ -165,9 +179,15 @@ if [ "$SAME_NAME_OLDEST" = "$SAME_NAME_LATEST" ] ; then
 
      cp -r $LATEST $OLDEST 2> /dev/null
 
-     echo -e "${GREEN}++ Moving: ${LATEST} to ${OLDEST}"
+       if [ "$flag" = 'true' ] ; then
 
-     sleep 1
+
+          [ -z $LATEST ] && echo "" &> /dev/null || echo -e "${GREEN}++ Moving: ${LATEST} to ${OLDEST}"
+
+          sleep 1
+
+       fi
+
 
 fi
 
